version: "3.8"

networks:
    internal:
        external: true
        name: internal-network

secrets:
    mysql_password:
        file: ~/docker/container_configs/keycloak/keycloak_db_password
    mysql_root_password:
        file: ~/docker/container_configs/keycloak/keycloak_db_root_password

services:
    # keycloak db
    mysql:
        image: mysql:8.0
        networks:
            - internal
        volumes:
            - ~/docker/container_storage/auth/db:/var/lib/mysql
        secrets:
            - mysql_password
            - mysql_root_password
        environment:
            - MYSQL_DATABASE=keycloak
            - MYSQL_USER=keycloak
            - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password

    # openid
    keycloak:
        image: quay.io/keycloak/keycloak:22.0.4
        depends_on:
            - mysql
        networks:
            - internal
        ports:
            - "8085:8085"
            - "9990:9990"
        environment:
            - KEYCLOAK_ADMIN=cloakAdmin
            - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
            - KC_DB=mysql
            - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak
            - KC_DB_USERNAME=keycloak
            - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
            - KC_HTTP_ENABLED=true
            - KC_HOSTNAME_STRICT=false
            - KC_PROXY_ADDRESS_FORWARDING=true
            - KC_PROXY=edge
        volumes:
            - ~/docker/container_storage/auth/realms:/opt/keycloak/data/realms
        command: export --file /opt/keycloak/data/realms/item.json --realm item

    # proxy
    nginx:
        image: nginx:1.25
        container_name: cnewbywa.auth
        networks:
            - internal
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/ssl:/etc/nginx/certs
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
